name: AI Daily Commit Loop

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 3PM UTC (adjust to your local time)
  workflow_dispatch:      # Allows manual triggering via GitHub UI

jobs:
  ai-self-dev-loop:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🤖 Run AI Dev Loop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python ai_committer/main.py

      - name: ✅ Commit and push changes
        run: |
          git config --global user.name "levelup-ai-bot"
          git config --global user.email "levelup-bot@example.com"
          git add .
          git commit -m "🤖 Daily self-evolving progress"
          git push || echo "Nothing to commit"
